addSbtPlugin("com.github.sbt"    % "sbt-native-packager"  % "1.9.16")
addSbtPlugin("com.julianpeeters" % "sbt-avrohugger"       % "2.4.0")
addSbtPlugin("com.eed3si9n"      % "sbt-assembly"         % "2.1.1")
addSbtPlugin("net.virtual-void"  % "sbt-dependency-graph" % "0.10.0-RC1")
addSbtPlugin("org.scoverage"     % "sbt-scoverage"        % "2.0.7")
